version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - ${POSTGRESQL_SERVER_PORT}:${POSTGRESQL_SERVER_PORT}